using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Pizzeria.Data;
using Pizzeria.Models;
using Pizzeria.Tests.TestSupport;

namespace Pizzeria.Tests;

/// <summary>
/// Model configuration checked on EF metadata and on SQLite in memory (RF-20, RF-21, RF-22).
/// SQLite does not enforce lengths or decimal precision, so those are asserted on the model.
/// </summary>
public class AppDbContextTests : IDisposable
{
    private readonly SqliteTestDatabase _database = new();

    public void Dispose() => _database.Dispose();

    private IProperty Property<TEntity>(AppDbContext context, string propertyName)
    {
        var entityType = context.Model.FindEntityType(typeof(TEntity));
        Assert.NotNull(entityType);

        var property = entityType!.FindProperty(propertyName);
        Assert.True(property is not null, $"{typeof(TEntity).Name}.{propertyName} is not mapped.");
        return property!;
    }

    // ---------- RF-22: context ----------

    // RF-22: the model is created without errors on SQLite in memory (EnsureCreated).
    [Fact]
    public async Task Model_IsCreatedOnSqliteInMemory_RF22()
    {
        await using var context = _database.CreateContext();

        Assert.True(await context.Database.CanConnectAsync());
        Assert.Equal(0, await context.MenuItems.CountAsync());
        Assert.Equal(0, await context.ContactMessages.CountAsync());
    }

    // RF-22: exactly two entities, exposed as MenuItems and ContactMessages.
    [Fact]
    public void Model_HasOnlyTheTwoEntities_RF22()
    {
        using var context = _database.CreateContext();

        DbSet<MenuItem> menuItems = context.MenuItems;
        DbSet<ContactMessage> contactMessages = context.ContactMessages;

        Assert.NotNull(menuItems);
        Assert.NotNull(contactMessages);
        Assert.Equal(
            [typeof(ContactMessage), typeof(MenuItem)],
            context.Model.GetEntityTypes().Select(e => e.ClrType).OrderBy(t => t.Name));
    }

    // RF-22 (negative): tests never run against SQL Server (RNF-28).
    [Fact]
    public void TestContext_UsesSqliteProvider_RNF28()
    {
        using var context = _database.CreateContext();

        Assert.Equal("Microsoft.EntityFrameworkCore.Sqlite", context.Database.ProviderName);
    }

    // ---------- RF-20: MenuItem ----------

    // RF-20: maximum lengths 80, 300, 20 and 200.
    [Theory]
    [InlineData(nameof(MenuItem.Name), 80)]
    [InlineData(nameof(MenuItem.Description), 300)]
    [InlineData(nameof(MenuItem.Category), 20)]
    [InlineData(nameof(MenuItem.ImagePath), 200)]
    public void MenuItem_MaxLengths_RF20(string propertyName, int expected)
    {
        using var context = _database.CreateContext();

        Assert.Equal(expected, Property<MenuItem>(context, propertyName).GetMaxLength());
    }

    // RF-20: Price is decimal(10,2).
    [Fact]
    public void MenuItem_Price_HasPrecision10Scale2_RF20()
    {
        using var context = _database.CreateContext();
        var price = Property<MenuItem>(context, nameof(MenuItem.Price));

        Assert.Equal(typeof(decimal), price.ClrType);
        Assert.Equal(10, price.GetPrecision());
        Assert.Equal(2, price.GetScale());
    }

    // RF-20: required and optional columns.
    [Theory]
    [InlineData(nameof(MenuItem.Name), false)]
    [InlineData(nameof(MenuItem.Description), true)]
    [InlineData(nameof(MenuItem.Price), false)]
    [InlineData(nameof(MenuItem.Category), false)]
    [InlineData(nameof(MenuItem.ImagePath), true)]
    [InlineData(nameof(MenuItem.IsFeatured), false)]
    public void MenuItem_Nullability_RF20(string propertyName, bool expectedNullable)
    {
        using var context = _database.CreateContext();

        Assert.Equal(expectedNullable, Property<MenuItem>(context, propertyName).IsNullable);
    }

    // RF-20: Id is an int primary key generated by the database.
    [Fact]
    public void MenuItem_Id_IsGeneratedIntKey_RF20()
    {
        using var context = _database.CreateContext();
        var id = Property<MenuItem>(context, nameof(MenuItem.Id));

        Assert.Equal(typeof(int), id.ClrType);
        Assert.True(id.IsPrimaryKey());
        Assert.Equal(ValueGenerated.OnAdd, id.ValueGenerated);
    }

    // RF-20: Category is stored as text (HasConversion<string>()).
    [Fact]
    public void MenuItem_Category_IsStoredAsString_RF20()
    {
        using var context = _database.CreateContext();
        var category = Property<MenuItem>(context, nameof(MenuItem.Category));

        Assert.Equal(typeof(MenuCategory), category.ClrType);
        Assert.Equal(typeof(string), category.GetTypeMapping().Converter?.ProviderClrType);
    }

    // RF-20: the enum has exactly Pizza, Starter, Drink, Dessert, in that order (S-3).
    [Fact]
    public void MenuCategory_HasTheFourValuesInOrder_RF20()
    {
        Assert.Equal(
            [MenuCategory.Pizza, MenuCategory.Starter, MenuCategory.Drink, MenuCategory.Dessert],
            Enum.GetValues<MenuCategory>());
        Assert.Equal(["Pizza", "Starter", "Drink", "Dessert"], Enum.GetNames<MenuCategory>());
    }

    // RF-20: every enum name fits in the nvarchar(20) column.
    [Fact]
    public void MenuCategory_NamesFitInColumn_RF20()
    {
        Assert.All(Enum.GetNames<MenuCategory>(), name => Assert.InRange(name.Length, 1, 20));
    }

    // RF-20: there is an index on Category.
    [Fact]
    public void MenuItem_HasIndexOnCategory_RF20()
    {
        using var context = _database.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(MenuItem))!;

        Assert.Contains(
            entityType.GetIndexes(),
            index => index.Properties.Count == 1 && index.Properties[0].Name == nameof(MenuItem.Category));
    }

    // RF-20: IsFeatured is false unless set.
    [Fact]
    public async Task MenuItem_IsFeatured_DefaultsToFalse_RF20()
    {
        await using (var context = _database.CreateContext())
        {
            context.MenuItems.Add(new MenuItem { Name = "Carnes", Price = 10500m, Category = MenuCategory.Pizza });
            await context.SaveChangesAsync();
        }

        await using var readContext = _database.CreateContext();
        var saved = await readContext.MenuItems.AsNoTracking().SingleAsync();

        Assert.False(saved.IsFeatured);
    }

    // RF-20: a full row survives a round trip, including the enum and the decimal price.
    [Fact]
    public async Task MenuItem_RoundTrip_RF20()
    {
        await using (var context = _database.CreateContext())
        {
            context.MenuItems.Add(new MenuItem
            {
                Name = "Tiramisu",
                Description = "Example description",
                Price = 8500.50m,
                Category = MenuCategory.Dessert,
                ImagePath = "img/tiramisu.webp",
                IsFeatured = true,
            });
            await context.SaveChangesAsync();
        }

        await using var readContext = _database.CreateContext();
        var saved = await readContext.MenuItems.AsNoTracking().SingleAsync();

        Assert.True(saved.Id > 0);
        Assert.Equal("Tiramisu", saved.Name);
        Assert.Equal("Example description", saved.Description);
        Assert.Equal(8500.50m, saved.Price);
        Assert.Equal(MenuCategory.Dessert, saved.Category);
        Assert.Equal("img/tiramisu.webp", saved.ImagePath);
        Assert.True(saved.IsFeatured);
    }

    // RF-20 (negative): properties that are not part of the model.
    [Fact]
    public void MenuItem_HasOnlyTheSpecifiedProperties_RF20()
    {
        using var context = _database.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(MenuItem))!;

        Assert.Equal(
            ["Category", "Description", "Id", "ImagePath", "IsFeatured", "Name", "Price"],
            entityType.GetProperties().Select(p => p.Name).Order(StringComparer.Ordinal));
    }

    // ---------- RF-21: ContactMessage ----------

    // RF-21: maximum lengths 80, 20, 254 and 1000.
    [Theory]
    [InlineData(nameof(ContactMessage.Name), 80)]
    [InlineData(nameof(ContactMessage.Phone), 20)]
    [InlineData(nameof(ContactMessage.Email), 254)]
    [InlineData(nameof(ContactMessage.Message), 1000)]
    public void ContactMessage_MaxLengths_RF21(string propertyName, int expected)
    {
        using var context = _database.CreateContext();

        Assert.Equal(expected, Property<ContactMessage>(context, propertyName).GetMaxLength());
    }

    // RF-21: required and optional columns.
    [Theory]
    [InlineData(nameof(ContactMessage.Name), false)]
    [InlineData(nameof(ContactMessage.Phone), true)]
    [InlineData(nameof(ContactMessage.Email), true)]
    [InlineData(nameof(ContactMessage.Message), false)]
    [InlineData(nameof(ContactMessage.CreatedAtUtc), false)]
    public void ContactMessage_Nullability_RF21(string propertyName, bool expectedNullable)
    {
        using var context = _database.CreateContext();

        Assert.Equal(expectedNullable, Property<ContactMessage>(context, propertyName).IsNullable);
    }

    // RF-21: Id is an int primary key generated by the database; CreatedAtUtc is a DateTime.
    [Fact]
    public void ContactMessage_IdAndCreatedAtUtc_Types_RF21()
    {
        using var context = _database.CreateContext();
        var id = Property<ContactMessage>(context, nameof(ContactMessage.Id));
        var createdAtUtc = Property<ContactMessage>(context, nameof(ContactMessage.CreatedAtUtc));

        Assert.Equal(typeof(int), id.ClrType);
        Assert.True(id.IsPrimaryKey());
        Assert.Equal(ValueGenerated.OnAdd, id.ValueGenerated);
        Assert.Equal(typeof(DateTime), createdAtUtc.ClrType);
    }

    // RF-21 (negative): no IP, no user agent, nothing beyond the specified columns.
    [Fact]
    public void ContactMessage_HasOnlyTheSpecifiedProperties_RF21()
    {
        using var context = _database.CreateContext();
        var entityType = context.Model.FindEntityType(typeof(ContactMessage))!;

        Assert.Equal(
            ["CreatedAtUtc", "Email", "Id", "Message", "Name", "Phone"],
            entityType.GetProperties().Select(p => p.Name).Order(StringComparer.Ordinal));
    }

    // RF-21: a row with only the required values is stored; optional ones stay null.
    [Fact]
    public async Task ContactMessage_RoundTrip_WithOptionalValuesNull_RF21()
    {
        var createdAtUtc = new DateTime(2026, 10, 3, 15, 0, 0, DateTimeKind.Utc);

        await using (var context = _database.CreateContext())
        {
            context.ContactMessages.Add(new ContactMessage
            {
                Name = "Ana",
                Message = "Quiero reservar",
                CreatedAtUtc = createdAtUtc,
            });
            await context.SaveChangesAsync();
        }

        await using var readContext = _database.CreateContext();
        var saved = await readContext.ContactMessages.AsNoTracking().SingleAsync();

        Assert.True(saved.Id > 0);
        Assert.Equal("Ana", saved.Name);
        Assert.Null(saved.Phone);
        Assert.Null(saved.Email);
        Assert.Equal("Quiero reservar", saved.Message);
        Assert.Equal(createdAtUtc, saved.CreatedAtUtc);
    }
}
